### ISSUE TITLE
[UX] Improve Dark Mode Color Scheme

### ISSUE THREAD

**Issue by LaDoger** [marcusschiesser/unc#11]
Current dark mode color looks weird. I suggest we choose another color scheme.

![image](https://github.com/marcusschiesser/unc/assets/60722582/2e7ab84f-4379-4f1c-9cd1-b0d6691b5dd6)

**Comment by marcusschiesser** [comment]
Yes I agree, easiest solution would be to remove this feature - @LaDoger what do you think?

**Comment by LaDoger** [comment]
Can't we just change some CSS in the code? If a lot of work, then should just remove for now.

**Comment by marcusschiesser** [comment]
done in https://github.com/marcusschiesser/unc-llamaindex
