### ISSUE TITLE
[Refactor] Use UI component library

### ISSUE THREAD

**Issue by marcusschiesser** [marcusschiesser/unc#13]
Currently, we're using self-made UI components (`ui-lib.tsx`) this was a problem when we needed a drop-down menu - we had to add the one from [headless](https://headlessui.com/). As the target is a complicated enterprise UI, it's better to use an existing UI library.

Requirements:
1. Easily stylable for different customers (Unc is a white-label solution)
2. Sophisticated components that can be used in enterprise UIs. 

https://ui.shadcn.com/ looks like a promising candidate. @LaDoger and @thucpn what are valid alternatives?

**Comment by LaDoger** [comment]
@marcusschiesser @thucpn One of our guys suggests https://tailwindcss.com/

**Comment by marcusschiesser** [comment]
https://tailwindcss.com/ is not a component library - it's for styling. Actually, it's used by headless and shadcn. Shadcn is based on https://www.radix-ui.com/ 
 Here's a voice on shadcn:
 https://medium.com/front-end-weekly/seven-reasons-why-i-love-shadcn-ui-bccaee4ae46d
Another alternative recommended by @thucpn is https://nextui.org/

**Comment by marcusschiesser** [comment]
Also using TailwindCSS 😆

**Comment by marcusschiesser** [comment]
done in https://github.com/marcusschiesser/unc-llamaindex
