### ISSUE TITLE
[Refactor] Consider using Vercel AI

### ISSUE THREAD

**Issue by marcusschiesser** [marcusschiesser/unc#15]
see https://sdk.vercel.ai/

Next step: Analyze advantages and (disadvantages)

**Comment by LaDoger** [comment]
@marcusschiesser What's so amazing about Vercel?

**Comment by marcusschiesser** [comment]
From a quick analysis, we could greatly simplify the code in https://github.com/marcusschiesser/unc/blob/6c378cb9ac40212b9cad2b82312da8827601a785/app/client/platforms/llm/openai.ts - but this doesn't have a big priority

**Comment by marcusschiesser** [comment]
https://github.com/marcusschiesser/unc-llamaindex is not using it on purpose (as we need to stream JSONs)
