### ISSUE TITLE
[Feature] Support file upload in a bot's context

### ISSUE THREAD

**Issue by marcusschiesser** [marcusschiesser/unc#16]
**Is your feature request related to a problem? Please describe.**
Users usually have documents in their file system and not as URLs available. Support adding files to enhance a bot's context.

**Describe the solution you'd like**
Add the option to upload files to a bot's context.
In the edit bot dialog, add a new option called `file`. If selected, a `file` can be uploaded that is added to the context. 

_The edit dialog_:
<img width="909" alt="image" src="https://github.com/marcusschiesser/unc/assets/17126/fbc7fe1c-b336-462a-bec7-ffb4a514df7f">

**Comment by LaDoger** [comment]
Yes, there is huge demand for this feature from researchers. And ChatGPT and Poe both have this.
![image](https://github.com/marcusschiesser/unc/assets/60722582/1514818e-0486-4490-ba1d-3c9146655c66)
![image](https://github.com/marcusschiesser/unc/assets/60722582/6ebd465f-c03b-455e-9b74-aa070f0a8c08)

**Comment by LaDoger** [comment]
Will need to (at least) support these file types:
- `.txt`
- `.docx`
- `.csv`
- `.xlsx`
- `.pdf`

We can consider audio files as well later on.

**Comment by marcusschiesser** [comment]
@LaDoger yes, you're right. We should first add the feature to upload a document in the chat (not in the bot's context as originally specified by me).

I also think it's a good time to clean up the UI a bit:
![image](https://github.com/marcusschiesser/unc/assets/17126/16d67eb5-569d-4d60-bc69-552ae2733147)

What do you think of this one?

**Comment by LaDoger** [comment]
@marcusschiesser yeah this looks about right. although if the "clear" button is right next to the "upload files" button, maybe that would cause misclicks? not sure but I think its alright

**Comment by marcusschiesser** [comment]
@LaDoger yes that was also my concern. Any better idea?
How about we:
1. Move the settings button to the upper right corner (this feels right)
2. Keep the chat actions line and add the file upload button there?

I anyhow think that a UI designer should have a look at this UI.

**Comment by LaDoger** [comment]
@marcusschiesser poe puts the upload button on the right side. can just copy what they did
![image](https://github.com/marcusschiesser/unc/assets/60722582/3bf97d4e-270d-4b31-bdac-113b63c136e1)

**Comment by marcusschiesser** [comment]
yes I agree, they have the best UI. @thucpn lets do this layout, but of course use free icons

**Comment by marcusschiesser** [comment]
done in https://github.com/marcusschiesser/unc-llamaindex
