### ISSUE TITLE
[Feature] Make Default Bots Removable

### ISSUE THREAD

**Issue by LaDoger** [marcusschiesser/unc#19]
Why are these things doing here? I never use them! Please make them removable because they trigger my minimalist OCD.
![image](https://github.com/marcusschiesser/unc/assets/60722582/d47a777e-3522-4458-b1ad-d0e5f4aae990)

**Comment by marcusschiesser** [comment]
Yes, that's a good idea. Code changes:
1. Check if a user has the default bots in the local storage. If they are not there, then copy the default bots from `BUILTIN_BOTS` to their local storage
2. Don't add `BUILTIN_BOTS` to the visible bot list - this will turn default bots into standard read-only bots (already deletable).
**Danger**: Shared bots are also read-only bots - make sure they are still working as expected - while doing the change rename `builtin` into `readOnly`

**Comment by marcusschiesser** [comment]
implemented in https://github.com/marcusschiesser/unc-llamaindex
