### ISSUE TITLE
[UX] Remove "With X contextual prompts" Tag

### ISSUE THREAD

**Issue by LaDoger** [marcusschiesser/unc#9]
It blocks content. Should remove to improve UX.

![image](https://github.com/marcusschiesser/unc/assets/60722582/8adae88d-0bad-45fc-b1d3-9e0560230d61)

**Comment by marcusschiesser** [comment]
The advantage is that we see that the bot is having context prompts in case we hide the context prompts. @LaDoger How valuable do you think this is?

**Comment by LaDoger** [comment]
@marcusschiesser It's a bit annoying when I scroll through the messages, but definitely not an urgent fix.

**Comment by marcusschiesser** [comment]
removed in https://github.com/marcusschiesser/unc-llamaindex
